import LocalizedStrings from 'react-native-localization';

const languageStrings = new LocalizedStrings({
    en: {
        'Enter your registered email to receive reset password code': 'Enter your registered email to receive reset password code',
        'Enter the 4-Digit code sent to you at': 'Enter the 4-Digit code sent to you at',
        'I agree with terms & condtion': 'I agree with terms & condtion',
        'Send code on phone number': 'Send code on phone number',
        'What are you looking for?': 'What are you looking for?',
        'Already have an account?': 'Already have an account?',
        'Don’t have an account?': 'Don’t have an account?',
        'CONFIRM NEW PASSWORD': 'CONFIRM NEW PASSWORD',
        'ENTER NEW PASSWORD': 'ENTER NEW PASSWORD',
        'What you’re into?': 'What you’re into?',
        'or continue with': 'or continue with',
        'Forgot Password?': 'Forgot Password?',
        'Congratulations!': 'Congratulations!',
        'Change password': 'Change password',
        'Created Groups': 'Created Groups',
        'Create a Group': 'Create a Group',
        'Joined Groups': 'Joined Groups',
        'Email address': 'Email address',
        'Place Holder': 'Place Holder',
        'Join a Group': 'Join a Group',
        'Rent a Buddy': 'Rent a Buddy',
        'Movie Night': 'Movie Night',
        'Remember me': 'Remember me',
        'Verify Code': 'Verify Code',
        'Send Code': 'Send Code',
        'Password': 'Password',
        'Calendar': 'Calendar',
        'Continue': 'Continue',
        'Wishlist': 'Wislist',
        'Created': 'Created',
        'Confirm': 'Confirm',
        'Sign In': 'Sign In',
        'Explore': 'Explore',
        'Sign up': 'Sign up',
        'Groups': 'Groups',
        'Joined': 'Joined',
        'Verify': 'Verify',
        'Resend': 'Resend',
        'Next': 'Next',
        'Home': 'Home',
        'Name': 'Name',
        'Skip': 'Skip',
        //Login Errors
        "wrong-email": "Email address not found",
        "wrong-password": "Incorrect email or password",
        "email-not-verify": "Verify your email or number first",
        //SignUp Errors
        "email-already-exist": "Email address is already registered",
        //Network request failed
        "network-reuest-error": "Network request failed",
        //Forget password
        "wrong-otp": "Incorrect otp",
        "otp-expired": "Your otp expired",
        //validtions yup
        "old-password-required": "Old password is required",
        "incorrect-old-password": "Incorrect old password",
        "confirm-password-required": "Confirm password is required",
        "password-required": "Password is required",
        "password-validation": "Must contain 6 characters, one uppercase, one lowercase, one number and one special case character",
        "email-required": "Email address is required",
        "email-not-valid": "Please enter valid email",
        "name-required": "Name is required",
        "name-min": "Name must be at least 3 characters long",
        "name-max": "Name should not be more than 18 characters",
        "password-not-match": "Password doesn't match",
        "number-min": "Number must be at least 11 digits long",
        "number-max": "Number should not be more than 18 digits",
        "number-required": "Number is required",
    },

    //text content for german language
    ger: {
        'Enter your registered email to receive reset password code': 'Geben Sie Ihre registrierte E-Mail-Adresse ein, um den Code zum Zurücksetzen des Passworts zu erhalten',
        'Enter the 4-Digit code sent to you at': 'Geben Sie den 4-stelligen Code ein, der Ihnen unter gesendet wurde',
        'I agree with terms & condtion': 'Ich stimme den Bedingungen zu',
        'Send code on phone number': 'Code auf Telefonnummer senden',
        'What are you looking for?': 'Wonach suchst du?',
        'Already have an account?': 'Sie haben bereits ein Konto?',
        'Don’t have an account?': 'Sie haben kein Konto?',
        'CONFIRM NEW PASSWORD': 'BESTÄTIGE NEUES PASSWORT',
        'ENTER NEW PASSWORD': 'NEUES PASSWORT EINGEBEN',
        'What you’re into?': 'Worauf stehst du?',
        'or continue with': 'oder weiter mit',
        'Forgot Password?': 'Passwort vergessen?',
        'Congratulations!': 'Herzliche Glückwünsche!',
        'Change password': 'Passwort ändern',
        'Created Groups': 'Gruppen erstellt',
        'Create a Group': 'Erstellen Sie eine Gruppe',
        'Joined Groups': 'Beigetretene Gruppen',
        'Email address': 'E-Mail-Addresse',
        'Place Holder': 'Platzhalter',
        'Join a Group': 'Einer Gruppe beitreten',
        'Rent a Buddy': 'Mieten Sie einen Kumpel',
        'Movie Night': 'Filmabend',
        'Remember me': 'Behalte mich in Erinnerung',
        'Verify Code': 'Code überprüfen',
        'Send Code': 'Code senden',
        'Password': 'Passwort',
        'Calendar': 'Kalender',
        'Continue': 'Fortsetzen',
        'Wishlist': 'Wunschzettel',
        'Created': 'Erstellt',
        'Confirm': 'Bestätigen',
        'Sign In': 'Anmelden',
        'Explore': 'Erkunden',
        'Sign up': 'Anmelden',
        'Groups': 'Gruppen',
        'Joined': 'Trat bei',
        'Verify': 'Verifizieren',
        'Resend': 'Erneut senden',
        'Next': 'Nächste',
        'Home': 'Zuhause',
        'Name': 'Name',
        'Skip': 'Überspringen',
    }
});

export default languageStrings;